### ISSUE TITLE
"amazon-pay-links-v2.s3-ap-northeast-1.amazonaws.com/index.html" return "Hello, Links!"

### ISSUE THREAD

**Issue by asonar-syamamoto** [amazonpay-labs/amazonpay-mobileapp-sample-v2#12]
下記コード部分で、チェックアウトの承認ができると思うのですが、スマホ側で動作するコードではawsのホストするページを使用しているようで、こちらが正常に動作せず、決済が完了できません。

https://github.com/amazonpay-labs/amazonpay-mobileapp-sample-v2/blob/e18a0786c399be87ea22509c3b3f711181808530/nodejs/views/sample/checkoutReview.ejs#L150-L154

ブラウザ側のコードはawsを介さないので、正常に動作します。
ブラウザ側もawsを介したコードに差し替えた場合は同様に"Hello Links!"が表示されてしまいます。

解決方法ご教示いただけないでしょうか？

**Comment by asonar-syamamoto** [comment]
android側は解決できました。

決済の承認をawsを介さずにintentにてアプリを起動するように修正しました。
修正内容下記の通りです。

amazonpay-mobileapp-sample-v2/nodejs/views/sample/checkoutReview.ejs
`


                    <div>
                        <% if(client === 'androidApp') { %>
                            <a class="btn btn-info btn-lg btn-block" href="intent://amazon_pay_android_v2/authorize#Intent;package=com.amazon.pay.sample.android_app_v2;scheme=amazon_pay_android_v2;S.secureWebviewSessionId=<%= _id %>;S.old_secureWebviewSessionId=<%= old_secureWebviewSessionId %>;end;">購　入</a>
                        <% } else if(client === 'iosApp') { %>
                            
                            <a class="btn btn-info btn-lg btn-block" href="https://amazon-pay-links-v2.s3-ap-northeast-1.amazonaws.com/index.html?secureWebviewSessionId=<%= _id %>&old_secureWebviewSessionId=<%= old_secureWebviewSessionId %>">購　入</a>
                        <% } else { %>
                            <a class="btn btn-info btn-lg btn-block" href="/authorize?secureWebviewSessionId=<%= _id %>&old_secureWebviewSessionId=<%= old_secureWebviewSessionId %>">購　入</a>
                        <% } %>
                    </div>

`

amazonpay-mobileapp-sample-v2/android/app/src/main/java/com/amazon/pay/sample/android_app_v2/AmazonPayActivity.java
`


    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_amazon_pay);

        Log.d("[onCreate]", "is calllllddddddd1!!!");

        Intent intent = getIntent();
        if (intent.getScheme().equals("https")) {
            // probably don't need this block
            String appLinkAction = intent.getAction();
            Uri appLinkData = intent.getData();
            Log.d("[AppLink]", appLinkAction);
            Log.d("[AppLink]", "" + appLinkData);

            Map<String, String> map = new HashMap<>();
            for (String kEqV : appLinkData.getEncodedQuery().split("&")) {
                String[] kv = kEqV.split("=");
                map.put(kv[0], kv[1]);
            }

            if (old_secureWebviewSessionId.equals(map.get("old_secureWebviewSessionId"))) {
                invokeAuthorizePage(getApplicationContext(), map.get("secureWebviewSessionId"));
            } else {
                webviewUrl = "/static/sample/error.html";
            }

        } else if (intent.getDataString().equals("amazon_pay_android_v2://amazon_pay_android_v2/authorize")) {
            Log.d("[DeepLink] data :", intent.getDataString());

            String secureWebviewSessionId = intent.getExtras().getString("secureWebviewSessionId");
            String oldSecureWebviewSessionId = intent.getExtras().getString("old_secureWebviewSessionId");

            Log.d("[DeepLink] params secureWebviewSessionId", secureWebviewSessionId);
            Log.d("[DeepLink] params old_secureWebviewSessionId", oldSecureWebviewSessionId);

            if (old_secureWebviewSessionId.equals(oldSecureWebviewSessionId)) {
                invokeAuthorizePage(getApplicationContext(), secureWebviewSessionId);
            } else {
                webviewUrl = "/static/sample/error.html";
            }
        } else {
            Log.d("[Intent]", "intent received!");
            webviewUrl = "/sample/thanks?secureWebviewSessionId=" + secureWebviewSessionId;
        }

        this.finish();
    }
`

**Comment by asonar-syamamoto** [comment]
ios側も同様の修正にて対応可能だと思います。

**Comment by tauty** [comment]
こちらでも事象が再現いたしました。
改修を行いますので、今しばらくお待ち下さい。

なお、「Intent」を代わりに使うことで対策を行ったとのことですが、こちらはユーザの秘密情報である「SessionID」をアプリに連携するタイミングであり、下記にも記載があります通り悪意のあるアプリが起動する可能性のある「Intent」はご使用にならないでください。
https://github.com/amazonpay-labs/amazonpay-mobileapp-sample-v2/tree/master/android#chrome-custom-tabssecure-webview--native%E3%81%AE%E8%B5%B7%E5%8B%95

iOS側も同様です。
https://github.com/amazonpay-labs/amazonpay-mobileapp-sample-v2/tree/master/ios#sfsafariviewcontrollersecure-webview--native%E3%81%AE%E8%B5%B7%E5%8B%95

※ 差し当たり、こちらでの改修が終わるまでの間、「Intent」を使って開発をすすめること自体は問題ございません。

**Comment by tauty** [comment]
Applinksの設定ファイルであるassetlinks.jsonの中に含まれるFingerprintが、ビルド環境によって変わってしまうことがあり、それによりApplinksの検証がマッチしなくなるのが原因でした。
サンプルアプリのインストール方法の中で、assetlinks.jsonを自分の環境用に生成する方法・配置する方法などの解説を下記に足しましたので、repositoryを最新に更新の上、試していただければ幸いです。

https://github.com/amazonpay-labs/amazonpay-mobileapp-sample-v2/tree/master/android#applinks%E3%81%AE%E8%A8%AD%E5%AE%9A
